[Config file]: config_files/8.json
[Unhandled Error] KeyError('action_type')
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 312, in test
    early_stop_flag, stop_info = early_stop(
  File "/root/script/webarena/run.py", line 198, in early_stop
    if last_action["action_type"] != ActionTypes.TYPE:
KeyError: 'action_type'
[Config file]: config_files/9.json
[Unhandled Error] KeyError('action_type')
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 312, in test
    early_stop_flag, stop_info = early_stop(
  File "/root/script/webarena/run.py", line 198, in early_stop
    if last_action["action_type"] != ActionTypes.TYPE:
KeyError: 'action_type'
[Config file]: config_files/9.json
[Unhandled Error] KeyError('action_type')
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 312, in test
    early_stop_flag, stop_info = early_stop(
  File "/root/script/webarena/run.py", line 198, in early_stop
    if last_action["action_type"] != ActionTypes.TYPE:
KeyError: 'action_type'
[Config file]: config_files/9.json
[Unhandled Error] KeyError('action_type')
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 312, in test
    early_stop_flag, stop_info = early_stop(
  File "/root/script/webarena/run.py", line 197, in early_stop
    print(last_action["action_type"])
KeyError: 'action_type'
[Config file]: config_files/7.json
[Unhandled Error] KeyError('action_type')
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 312, in test
    early_stop_flag, stop_info = early_stop(
  File "/root/script/webarena/run.py", line 198, in early_stop
    if last_action["action_type"] != ActionTypes.TYPE:
KeyError: 'action_type'
[Config file]: config_files/7.json
[Unhandled Error] KeyError('action_type')
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 315, in test
    early_stop_flag, stop_info = early_stop(
  File "/root/script/webarena/run.py", line 201, in early_stop
    if last_action["action_type"] != ActionTypes.TYPE:
KeyError: 'action_type'
[Config file]: config_files/7.json
[Unhandled Error] KeyError('action_type')
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 314, in test
    early_stop_flag, stop_info = early_stop(
  File "/root/script/webarena/run.py", line 200, in early_stop
    if last_action["action_type"] != ActionTypes.TYPE:
KeyError: 'action_type'
[Config file]: config_files/7.json
[Unhandled Error] FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 389, in test
    with open(format_traces_path,"w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/format_traces/7.json'
[Config file]: config_files/7.json
[Unhandled Error] AttributeError("'Logger' object has no attribute 'infor'")
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 391, in test
    logger.infor(f"[Format trace saved] Path: {format_traces_path}")
AttributeError: 'Logger' object has no attribute 'infor'. Did you mean: 'info'?
[Config file]: /tmp/tmp7baqjiwm/11.json
[Unhandled Error] LookupError("\n**********************************************************************\n  Resource \x1b[93mpunkt\x1b[0m not found.\n  Please use the NLTK Downloader to obtain the resource:\n\n  \x1b[31m>>> import nltk\n  >>> nltk.download('punkt')\n  \x1b[0m\n  For more information see: https://www.nltk.org/data.html\n\n  Attempted to load \x1b[93mtokenizers/punkt/PY3/english.pickle\x1b[0m\n\n  Searched in:\n    - '/root/nltk_data'\n    - '/root/miniconda3/envs/webarena/nltk_data'\n    - '/root/miniconda3/envs/webarena/share/nltk_data'\n    - '/root/miniconda3/envs/webarena/lib/nltk_data'\n    - '/usr/share/nltk_data'\n    - '/usr/local/share/nltk_data'\n    - '/usr/lib/nltk_data'\n    - '/usr/local/lib/nltk_data'\n    - ''\n**********************************************************************\n")
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 365, in test
    score = evaluator(
  File "<@beartype(evaluation_harness.evaluators.EvaluatorComb.__call__) at 0x7f8cde8b3490>", line 112, in __call__
  File "/root/script/webarena/evaluation_harness/evaluators.py", line 350, in __call__
    cur_score = evaluator(trajectory, config_file, page, client)
  File "/root/script/webarena/evaluation_harness/evaluators.py", line 145, in __call__
    score *= self.must_include(
  File "<@beartype(evaluation_harness.evaluators.StringEvaluator.must_include) at 0x7f8cde8b2b00>", line 69, in must_include
  File "/root/script/webarena/evaluation_harness/evaluators.py", line 106, in must_include
    and len(word_tokenize(clean_ref)) == 1
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 129, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = load(f"tokenizers/punkt/{language}.pickle")
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/data.py", line 876, in _open
    return find(path_, path + [""]).open()
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:
    - '/root/nltk_data'
    - '/root/miniconda3/envs/webarena/nltk_data'
    - '/root/miniconda3/envs/webarena/share/nltk_data'
    - '/root/miniconda3/envs/webarena/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

[Config file]: /tmp/tmp1d2hhcv8/11.json
[Unhandled Error] LookupError("\n**********************************************************************\n  Resource \x1b[93mpunkt\x1b[0m not found.\n  Please use the NLTK Downloader to obtain the resource:\n\n  \x1b[31m>>> import nltk\n  >>> nltk.download('punkt')\n  \x1b[0m\n  For more information see: https://www.nltk.org/data.html\n\n  Attempted to load \x1b[93mtokenizers/punkt/PY3/english.pickle\x1b[0m\n\n  Searched in:\n    - '/root/nltk_data'\n    - '/root/miniconda3/envs/webarena/nltk_data'\n    - '/root/miniconda3/envs/webarena/share/nltk_data'\n    - '/root/miniconda3/envs/webarena/lib/nltk_data'\n    - '/usr/share/nltk_data'\n    - '/usr/local/share/nltk_data'\n    - '/usr/lib/nltk_data'\n    - '/usr/local/lib/nltk_data'\n    - ''\n**********************************************************************\n")
Traceback (most recent call last):
  File "/root/script/webarena/run.py", line 365, in test
    score = evaluator(
  File "<@beartype(evaluation_harness.evaluators.EvaluatorComb.__call__) at 0x7f14e3093490>", line 112, in __call__
  File "/root/script/webarena/evaluation_harness/evaluators.py", line 350, in __call__
    cur_score = evaluator(trajectory, config_file, page, client)
  File "/root/script/webarena/evaluation_harness/evaluators.py", line 145, in __call__
    score *= self.must_include(
  File "<@beartype(evaluation_harness.evaluators.StringEvaluator.must_include) at 0x7f14e3092b00>", line 69, in must_include
  File "/root/script/webarena/evaluation_harness/evaluators.py", line 106, in must_include
    and len(word_tokenize(clean_ref)) == 1
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 129, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = load(f"tokenizers/punkt/{language}.pickle")
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/data.py", line 876, in _open
    return find(path_, path + [""]).open()
  File "/root/miniconda3/envs/webarena/lib/python3.10/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:
    - '/root/nltk_data'
    - '/root/miniconda3/envs/webarena/nltk_data'
    - '/root/miniconda3/envs/webarena/share/nltk_data'
    - '/root/miniconda3/envs/webarena/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

